(()=>{const recipes2={
'White Bread':{type:'bake',station:'Oven',needs:{Flour:2,Milk:1,Eggs:1},time:'Bake 30 min',stock:'White Bread'},
'Croissant':{type:'bake',station:'Oven',needs:{Flour:2,Butter:2,Milk:1},time:'Bake 22 min',stock:'Croissant'},
'Strawberry Cake':{type:'bake',station:'Oven',needs:{Flour:2,Eggs:2,Milk:1,Sugar:2,Strawberries:2},time:'Bake 40 min',stock:'Strawberry Cake'},
'Cookies':{type:'bake',station:'Oven',needs:{Flour:1,Butter:1,Sugar:1,Eggs:1},time:'Bake 15 min',stock:'Cookies'},
'Latte':{type:'drink',station:'Espresso machine',needs:{'Coffee Beans':1,Milk:1},time:'Brew & steam',stock:'Latte'},
'Peach Tea':{type:'drink',station:'Tea brewer',needs:{'Tea Leaves':1,Honey:1},time:'Steep tea',stock:'Peach Tea'},
'Berry Smoothie':{type:'drink',station:'Blender',needs:{Strawberries:2,Milk:1,Honey:1},time:'Blend',stock:'Berry Smoothie'}
};
for(const k of ['Flour','Milk','Eggs','Butter','Sugar','Strawberries','Coffee Beans','Tea Leaves','Honey'])if(state.inventory[k]==null)state.inventory[k]=6;save();let cook={recipe:'White Bread',added:{},mixed:false,cooking:false,ready:false};
function available(name){return state.inventory[name]||0}function requirementsMet(){const r=recipes2[cook.recipe];return Object.entries(r.needs).every(([k,n])=>(cook.added[k]||0)>=n)}
function openCooking(prefer){if(prefer){if(/coffee/i.test(prefer))cook.recipe='Latte';else if(/tea/i.test(prefer))cook.recipe='Peach Tea';else if(/smooth/i.test(prefer))cook.recipe='Berry Smoothie';else if(/cake|cupcake/i.test(prefer))cook.recipe='Strawberry Cake';else if(/cookie/i.test(prefer))cook.recipe='Cookies';else if(/pastry/i.test(prefer))cook.recipe='Croissant';else cook.recipe='White Bread'}cook.added={};cook.mixed=false;cook.cooking=false;cook.ready=false;renderCook()}
function renderCook(){const r=recipes2[cook.recipe],ingredients=Object.keys(r.needs);modal(`<div class="cooking-modal"><h2>Kitchen workshop <span class="stock-badge">Stock: ${state.stock[r.stock]||0}</span></h2><p class="sub">Drag ingredients into the ${r.type==='bake'?'mixing bowl':'drink machine'}.</p><div class="cook-layout"><aside class="recipe-book"><h3>Recipe book</h3>${Object.keys(recipes2).map(n=>`<button class="recipe-choice ${n===cook.recipe?'active':''}" data-recipe2="${n}">${n}</button>`).join('')}</aside><main class="cook-worktop"><h3>${cook.recipe}</h3>${cook.ready?`<div class="drop-station"><div class="finished-dish"></div><b class="finished-label">${r.stock} ready!</b></div><button class="cook-action" data-collect-dish>Collect finished item</button>`:`<div class="workstation"><div class="drop-station ${r.type==='bake'?'bowl':'drink'}" data-cook-drop="ingredients"><div class="machine"></div><p>${r.type==='bake'?'Mixing bowl':r.station}</p></div>${r.type==='bake'?`<div class="drop-station oven" data-cook-drop="oven"><div class="machine"></div><p>Oven</p></div>`:''}<div class="added-list">${Object.entries(cook.added).map(([k,n])=>`<span>${k} ×${n}</span>`).join('')}</div><button class="cook-action" data-cook-action ${!requirementsMet()||cook.cooking?'disabled':''}>${cook.mixed?'Place mixture in oven':r.type==='bake'?'Mix ingredients':r.time}</button></div>`}</main><aside class="pantry-board"><h3>Pantry</h3>${ingredients.map(k=>`<div class="ingredient-jar ${(cook.added[k]||0)>=r.needs[k]?'used':''}" draggable="true" data-ingredient="${k}"><span><b>${k}</b><small>${available(k)} available · need ${r.needs[k]}</small></span></div>`).join('')}<div class="cook-message">${requirementsMet()?'Everything is measured. Ready for the next step!':'Drag each required ingredient to the station.'}</div><ol class="recipe-steps"><li class="${requirementsMet()?'done':''}">Measure ingredients</li><li class="${cook.mixed?'done':''}">${r.type==='bake'?'Mix batter or dough':r.time}</li><li class="${cook.ready?'done':''}">${r.type==='bake'?r.time:'Serve drink'}</li></ol></aside></div></div>`)}
document.addEventListener('dragstart',e=>{const jar=e.target.closest('[data-ingredient]');if(jar)e.dataTransfer.setData('text/plain',jar.dataset.ingredient)});document.addEventListener('dragover',e=>{const drop=e.target.closest('[data-cook-drop]');if(drop){e.preventDefault();drop.classList.add('dragover')}});document.addEventListener('dragleave',e=>e.target.closest('[data-cook-drop]')?.classList.remove('dragover'));document.addEventListener('drop',e=>{const drop=e.target.closest('[data-cook-drop]');if(!drop)return;e.preventDefault();const ingredient=e.dataTransfer.getData('text/plain'),r=recipes2[cook.recipe];drop.classList.remove('dragover');if(drop.dataset.cookDrop==='ingredients'&&r.needs[ingredient]){if(available(ingredient)<=0){toast(`No ${ingredient} left`);return}if((cook.added[ingredient]||0)<r.needs[ingredient])cook.added[ingredient]=(cook.added[ingredient]||0)+1;renderCook()}else if(drop.dataset.cookDrop==='oven'&&ingredient==='Prepared mixture'&&cook.mixed)startCooking()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.recipe2){cook.recipe=b.dataset.recipe2;cook.added={};cook.mixed=false;cook.ready=false;renderCook()}if(b.dataset.cookAction!==undefined){const r=recipes2[cook.recipe];if(r.type==='bake'&&!cook.mixed){cook.mixed=true;renderCook();const bowl=document.querySelector('[data-cook-drop="ingredients"]');if(bowl){bowl.setAttribute('draggable','true');bowl.addEventListener('dragstart',ev=>ev.dataTransfer.setData('text/plain','Prepared mixture'),{once:true})}}else startCooking()}if(b.dataset.collectDish!==undefined){const r=recipes2[cook.recipe];state.stock[r.stock]=(state.stock[r.stock]||0)+3;state.minute+=r.type==='bake'?30:10;updateHUD();toast(`${r.stock} collected · +3 stock`);cook.ready=false;renderCook()}});
function startCooking(){const r=recipes2[cook.recipe];if(!requirementsMet())return;for(const[k,n]of Object.entries(r.needs))state.inventory[k]-=n;cook.cooking=true;renderCook();toast(`${r.time}…`);setTimeout(()=>{cook.cooking=false;cook.ready=true;renderCook()},r.type==='bake'?2200:1400);save()}
const previousInteract=interactPhysical;interactPhysical=function(el){if(current==='bakery'&&currentTab==='Kitchen'){const action=el.dataset.actionName||'',name=el.querySelector('.object-name')?.textContent||'';if(/Bake|Coffee|Tea|Smoothie|Oven|station|Blend/i.test(action+' '+name)){openCooking(action+' '+name);return}}previousInteract(el)};
})();
