(()=>{const recipes2={
'White Bread':{type:'bake',station:'Oven',needs:{Flour:2,Milk:1,Eggs:1},time:'Bake 30 min',stock:'White Bread'},
'Croissant':{type:'bake',station:'Oven',needs:{Flour:2,Butter:2,Milk:1},time:'Bake 22 min',stock:'Croissant'},
'Strawberry Cake':{type:'bake',station:'Oven',needs:{Flour:2,Eggs:2,Milk:1,Sugar:2,Strawberries:2},time:'Bake 40 min',stock:'Strawberry Cake'},
'Cookies':{type:'bake',station:'Oven',needs:{Flour:1,Butter:1,Sugar:1,Eggs:1},time:'Bake 15 min',stock:'Cookies'},
'Latte':{type:'drink',station:'Espresso machine',needs:{'Coffee Beans':1,Milk:1},time:'Brew & steam',stock:'Latte'},
'Peach Tea':{type:'drink',station:'Tea brewer',needs:{'Tea Leaves':1,Honey:1},time:'Steep tea',stock:'Peach Tea'},
'Berry Smoothie':{type:'drink',station:'Blender',needs:{Strawberries:2,Milk:1,Honey:1},time:'Blend',stock:'Berry Smoothie'},
'Apple Pie':{type:'bake',station:'Oven',needs:{Flour:2,Butter:1,Sugar:1,Apples:3,Cinnamon:1},time:'Bake 38 min',stock:'Apple Pie'},
'Blueberry Muffins':{type:'bake',station:'Oven',needs:{Flour:2,Eggs:1,Milk:1,Sugar:1,Blueberries:2},time:'Bake 24 min',stock:'Blueberry Muffins'},
'Cinnamon Rolls':{type:'bake',station:'Oven',needs:{Flour:2,Butter:1,Milk:1,Sugar:1,Cinnamon:2},time:'Bake 26 min',stock:'Cinnamon Rolls'},
'Lemon Cupcakes':{type:'bake',station:'Oven',needs:{Flour:2,Eggs:2,Sugar:1,Lemons:2,Vanilla:1},time:'Bake 22 min',stock:'Lemon Cupcakes'},
'Chocolate Cake':{type:'bake',station:'Oven',needs:{Flour:2,Eggs:2,Milk:1,Sugar:2,Cocoa:2},time:'Bake 42 min',stock:'Chocolate Cake'},
'Oat Honey Cookies':{type:'bake',station:'Oven',needs:{Oats:2,Butter:1,Honey:1,Eggs:1,Nuts:1},time:'Bake 17 min',stock:'Oat Honey Cookies'},
'Hot Chocolate':{type:'drink',station:'Drink machine',needs:{Cocoa:2,Milk:2,Sugar:1,Cream:1},time:'Heat & whisk',stock:'Hot Chocolate'},
'Vanilla Frappe':{type:'drink',station:'Blender',needs:{'Coffee Beans':1,Milk:1,Cream:1,Vanilla:1,Sugar:1},time:'Blend frappe',stock:'Vanilla Frappe'},
'Peach Smoothie':{type:'drink',station:'Blender',needs:{Peaches:2,Yogurt:1,Honey:1},time:'Blend smoothie',stock:'Peach Smoothie'},
'Spiced Apple Cider':{type:'drink',station:'Tea brewer',needs:{Apples:3,Cinnamon:1,Honey:1},time:'Warm & steep',stock:'Spiced Apple Cider'},
'Caramel Latte':{type:'drink',station:'Espresso machine',needs:{'Coffee Beans':1,Milk:1,Caramel:1,Cream:1},time:'Brew & steam',stock:'Caramel Latte'}
};
for(const k of ['Flour','Milk','Eggs','Butter','Sugar','Strawberries','Coffee Beans','Tea Leaves','Honey','Apples','Blueberries','Cinnamon','Vanilla','Lemons','Cream','Cocoa','Peaches','Yogurt','Oats','Nuts','Caramel'])if(state.inventory[k]==null)state.inventory[k]=6;save();let cook={recipe:'White Bread',category:'Bread station',added:{},mixed:false,cooking:false,ready:false};
function available(name){return state.inventory[name]||0}function requirementsMet(){const r=recipes2[cook.recipe];return Object.entries(r.needs).every(([k,n])=>(cook.added[k]||0)>=n)}
const stationRecipes={
  'Bread station':['White Bread','Cinnamon Rolls'],
  'Pastry station':['Croissant','Blueberry Muffins','Apple Pie'],
  'Cake station':['Strawberry Cake','Chocolate Cake'],
  'Cupcake station':['Lemon Cupcakes','Blueberry Muffins'],
  'Cookie station':['Cookies','Oat Honey Cookies'],
  'Pie station':['Apple Pie'],
  'Coffee station':['Latte','Caramel Latte','Hot Chocolate','Vanilla Frappe'],
  'Tea station':['Peach Tea','Spiced Apple Cider'],
  'Smoothie station':['Berry Smoothie','Peach Smoothie'],
  'Ovens':Object.keys(recipes2).filter(name=>recipes2[name].type==='bake')
};
function categoryFor(prefer=''){const label=Object.keys(stationRecipes).sort((a,b)=>b.length-a.length).find(name=>new RegExp(name.replace(/ station$/i,''),'i').test(prefer));return label||(/oven|bake/i.test(prefer)?'Ovens':'Bread station')}
function openCooking(prefer){cook.category=categoryFor(prefer);const choices=stationRecipes[cook.category];cook.recipe=choices[0];cook.added={};cook.mixed=false;cook.cooking=false;cook.ready=false;renderCook()}
function renderCook(){const r=recipes2[cook.recipe],ingredients=Object.keys(r.needs),choices=stationRecipes[cook.category]||Object.keys(recipes2);modal(`<div class="cooking-modal"><h2>Kitchen workshop <span class="stock-badge">Stock: ${state.stock[r.stock]||0}</span></h2><p class="sub">${cook.category} · Drag only the required ingredients into the ${r.type==='bake'?'mixing bowl':'drink machine'}.</p><div class="cook-layout"><aside class="recipe-book"><h3>${cook.category}</h3><p class="station-helper">Recipes made at this station</p>${choices.map(n=>`<button class="recipe-choice ${n===cook.recipe?'active':''}" data-recipe2="${n}">${n}</button>`).join('')}</aside><main class="cook-worktop"><h3>${cook.recipe}</h3>${cook.ready?`<div class="drop-station"><div class="finished-dish ${r.stock==='Apple Pie'?'finished-pie':''}" role="img" aria-label="${r.stock}"></div><b class="finished-label">${r.stock} ready!</b></div><button class="cook-action" data-collect-dish>Collect finished item</button>`:`<div class="workstation"><div class="drop-station ${r.type==='bake'?'bowl':'drink'}" data-cook-drop="ingredients"><div class="machine"></div><p>${r.type==='bake'?'Mixing bowl':r.station}</p></div>${r.type==='bake'?`<div class="drop-station oven" data-cook-drop="oven"><div class="machine"></div><p>Oven</p></div>`:''}<div class="added-list">${Object.entries(cook.added).map(([k,n])=>`<span>${k} ×${n}</span>`).join('')}</div><button class="cook-action" data-cook-action ${!requirementsMet()||cook.cooking?'disabled':''}>${cook.mixed?'Place mixture in oven':r.type==='bake'?'Mix ingredients':r.time}</button></div>`}</main><aside class="pantry-board"><h3>${cook.category} ingredients</h3><p class="station-helper">Only this recipe's ingredients</p>${ingredients.map(k=>`<div class="ingredient-jar ${(cook.added[k]||0)>=r.needs[k]?'used':''}" draggable="true" data-ingredient="${k}"><span><b>${k}</b><small>${available(k)} available · need ${r.needs[k]}</small></span></div>`).join('')}<div class="cook-message">${requirementsMet()?'Everything is measured. Ready for the next step!':'Drag each required ingredient to the station.'}</div><ol class="recipe-steps"><li class="${requirementsMet()?'done':''}">Measure ingredients</li><li class="${cook.mixed?'done':''}">${r.type==='bake'?'Mix batter or dough':r.time}</li><li class="${cook.ready?'done':''}">${r.type==='bake'?r.time:'Serve drink'}</li></ol></aside></div></div>`)}
document.addEventListener('dragstart',e=>{const jar=e.target.closest('[data-ingredient]');if(jar)e.dataTransfer.setData('text/plain',jar.dataset.ingredient)});document.addEventListener('dragover',e=>{const drop=e.target.closest('[data-cook-drop]');if(drop){e.preventDefault();drop.classList.add('dragover')}});document.addEventListener('dragleave',e=>e.target.closest('[data-cook-drop]')?.classList.remove('dragover'));document.addEventListener('drop',e=>{const drop=e.target.closest('[data-cook-drop]');if(!drop)return;e.preventDefault();const ingredient=e.dataTransfer.getData('text/plain'),r=recipes2[cook.recipe];drop.classList.remove('dragover');if(drop.dataset.cookDrop==='ingredients'&&r.needs[ingredient]){if(available(ingredient)<=0){toast(`No ${ingredient} left`);return}if((cook.added[ingredient]||0)<r.needs[ingredient])cook.added[ingredient]=(cook.added[ingredient]||0)+1;renderCook()}else if(drop.dataset.cookDrop==='oven'&&ingredient==='Prepared mixture'&&cook.mixed)startCooking()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.recipe2){cook.recipe=b.dataset.recipe2;cook.added={};cook.mixed=false;cook.ready=false;renderCook()}if(b.dataset.cookAction!==undefined){const r=recipes2[cook.recipe];if(r.type==='bake'&&!cook.mixed){cook.mixed=true;renderCook();const bowl=document.querySelector('[data-cook-drop="ingredients"]');if(bowl){bowl.setAttribute('draggable','true');bowl.addEventListener('dragstart',ev=>ev.dataTransfer.setData('text/plain','Prepared mixture'),{once:true})}}else startCooking()}if(b.dataset.collectDish!==undefined){const r=recipes2[cook.recipe];state.stock[r.stock]=(state.stock[r.stock]||0)+3;state.minute+=r.type==='bake'?30:10;updateHUD();toast(`${r.stock} collected · +3 stock`);cook.ready=false;renderCook()}});
function startCooking(){const r=recipes2[cook.recipe];if(!requirementsMet())return;for(const[k,n]of Object.entries(r.needs))state.inventory[k]-=n;cook.cooking=true;renderCook();toast(`${r.time}…`);setTimeout(()=>{cook.cooking=false;cook.ready=true;renderCook()},r.type==='bake'?2200:1400);save()}
const previousKitchenRender=renderRoom;renderRoom=function(){previousKitchenRender();if(current==='bakery'&&currentTab==='Kitchen'&&(state.stock['Apple Pie']||0)>0)document.querySelector('.physical-shell')?.insertAdjacentHTML('beforeend','<div class="finished-pie-product" role="img" aria-label="One finished apple pie on the serving table"></div>')};
const previousInteract=interactPhysical;interactPhysical=function(el){if(current==='bakery'&&currentTab==='Kitchen'){const action=el.dataset.actionName||'',name=el.querySelector('.object-name')?.textContent||'';if(/Bake|Coffee|Tea|Smoothie|Oven|Bread|Pastry|Cake|Cupcake|Cookie|Pie|Blend/i.test(action+' '+name)){openCooking(action+' '+name);return}}previousInteract(el)};
})();
