const physicalRooms={
'bakery|Café':[['Front counter','counter','Open bakery'],['Register','register','Start Shift'],['Cake display','display','Browse cakes'],['Bread shelves','shelf','Browse bread'],['Pastry case','display','Browse pastries'],['Cookie shelves','shelf','Browse cookies'],['Espresso machine','coffee','Make coffee'],['Tea and honey bar','shelf','Make tea'],['Dining table','table','Sit'],['Booth seating','sofa','Sit'],['Piano','art','Play piano'],['Kitchen door','door','Enter Kitchen']],
'bakery|Kitchen':[['Bread station','counter','Bake Bread'],['Pastry station','counter','Bake Pastry'],['Cake station','counter','Bake Cake'],['Cupcake station','counter','Bake Cupcakes'],['Cookie station','counter','Bake Cookies'],['Pie station','counter','Bake Pie'],['Sandwich station','counter','Make Sandwich'],['Coffee station','coffee','Make Coffee'],['Tea station','shelf','Make Tea'],['Smoothie station','coffee','Blend Smoothie'],['Packaging','counter','Package Order'],['Ingredient storage','shelf','View Ingredients'],['Pantry','shelf','Open Pantry'],['Refrigerator','fridge','Open Refrigerator'],['Ovens','oven','Bake'],['Serving table','table','Collect Food']],
'cottage|Living room':[['Cottage sofa','sofa','Sit'],['Armchair','sofa','Sit'],['Coffee table','table','Eat Meal'],['Fireplace','fireplace','Relax'],['Television','art','Watch TV'],['Bookshelf','shelf','Read'],['Indoor plants','plant','Water Plants'],['Pet bed','bed','Pet Companion']],
'cottage|Kitchen':[['Refrigerator','fridge','Open'],['Stove','oven','Cook Meal'],['Sink','counter','Wash Hands'],['Cabinets','shelf','Browse'],['Dining table','table','Eat Meal'],['Pantry','shelf','Open'],['Tea kettle','coffee','Make Tea'],['Coffee machine','coffee','Make Coffee']],
'cottage|Bedroom':[['Cottage bed','bed','Sleep and Save'],['Nightstand','table','Use'],['Wardrobe','rack','Change Outfit'],['Vanity','table','Customize'],['Mirror','art','View Outfit'],['Window plant','plant','Water']],
'cottage|Bathroom':[['Shower','door','Shower'],['Sink','counter','Wash Hands'],['Toilet','fridge','Use'],['Towel rack','rack','Use Towel']],
'shops|Market':[['Shopping carts','rack','Take Cart'],['Fresh produce','shelf','Add Produce'],['Milk and eggs','fridge','Add Dairy'],['Flour and sugar','shelf','Add Baking Goods'],['Chocolate','shelf','Add Chocolate'],['Tea and coffee','shelf','Add Drinks'],['Frozen foods','fridge','Add Frozen Food'],['Bakery supplies','shelf','Add Supplies'],['Cleaning supplies','shelf','Add Cleaning'],['Decorations','shelf','Add Decoration'],['Checkout','checkout','Checkout']],
'shops|Pet shop':[['Dogs','animal','Meet Dogs'],['Cats','animal','Meet Cats'],['Birds','animal','Meet Birds'],['Rabbits','animal','Meet Rabbits'],['Hamsters','animal','Meet Hamsters'],['Fish tanks','display','View Fish'],['Pet toys','shelf','Buy Toys'],['Pet beds','bed','Buy Bed'],['Pet food','shelf','Buy Food'],['Pet clothing','rack','Buy Clothing'],['Play area','sofa','Play']],
'shops|Furniture':[['Living room display','sofa','Shop Living Room'],['Bedroom display','bed','Shop Bedroom'],['Kitchen display','counter','Shop Kitchen'],['Bathroom display','rack','Shop Bathroom'],['Garden display','plant','Shop Garden'],['Pet furniture','bed','Shop Pet Furniture']],
'shops|Boutique':[['Women clothing','rack','Try On'],['Men clothing','rack','Try On'],['Shoes','shelf','Try On'],['Accessories','shelf','Try On'],['Hats','shelf','Try On'],['Jewelry','display','Try On'],['Changing room','door','Change'],['Mirror','art','View Outfit'],['Cashier','checkout','Buy Outfit']],
'park|Pavilion':[['Tea tables','table','Host Tea Party'],['Tea set','display','Pour Tea'],['Cake stand','display','Serve Cake'],['Flower garden','plant','Arrange Flowers'],['Picnic area','sofa','Picnic'],['Butterfly garden','plant','Catch Butterfly'],['Duck pond','display','Feed Ducks'],['Mini games','art','Play'],['Playground','sofa','Play'],['Food stand','counter','Buy Snack']],
'library|Reading Hall':[['Bookshelves','shelf','Browse Books'],['Fireplace','fireplace','Read by Fire'],['Reading chairs','sofa','Read'],['Study tables','table','Study'],['Recipe books','shelf','Unlock Recipe'],['Magazine rack','rack','Browse'],['Tea corner','coffee','Make Tea']],
'greenhouse|Greenhouse':[['Flower beds','plant','Grow Flowers'],['Vegetable beds','plant','Grow Vegetables'],['Herb shelves','shelf','Grow Herbs'],['Fruit trees','plant','Harvest Fruit'],['Seed cabinet','shelf','Buy Seeds'],['Watering area','counter','Water Crops']],
'giftshop|Gift Shop':[['Greeting cards','shelf','Buy Card'],['Gift wrap','counter','Wrap Gift'],['Flowers','plant','Buy Flowers'],['Stuffed animals','animal','Buy Gift'],['Candles','shelf','Buy Candle'],['Picture frames','art','Buy Frame'],['Holiday gifts','shelf','Buy Gift']],
'delivery|Delivery Center':[['Delivery board','art','Accept Job'],['Packages','shelf','Collect Package'],['Scooters','rack','Choose Vehicle'],['Reward counter','checkout','Complete Job']],
'studio|Art Studio':[['Painting counter','art','Paint'],['Pottery wheel','table','Make Pottery'],['Craft table','counter','Craft Decoration'],['Display gallery','art','View Art']]
};
Object.assign(locations,{library:{kicker:'LIBRARY',title:'Willow Library',desc:'',tabs:['Reading Hall'],bg:'',rooms:{'Reading Hall':[]}},greenhouse:{kicker:'GREENHOUSE',title:'Glassleaf Greenhouse',desc:'',tabs:['Greenhouse'],bg:'',rooms:{Greenhouse:[]}},giftshop:{kicker:'GIFT SHOP',title:'Petal & Parcel',desc:'',tabs:['Gift Shop'],bg:'',rooms:{'Gift Shop':[]}},delivery:{kicker:'DELIVERY',title:'Village Delivery Center',desc:'',tabs:['Delivery Center'],bg:'',rooms:{'Delivery Center':[]}},studio:{kicker:'ART STUDIO',title:'Mosslight Studio',desc:'',tabs:['Art Studio'],bg:'',rooms:{'Art Studio':[]}}});
locations.cottage.tabs=['Living room','Kitchen','Bedroom','Bathroom'];locations.cottage.rooms.Kitchen=[];locations.cottage.rooms.Bedroom=[];locations.cottage.rooms.Bathroom=[];locations.shops.tabs=['Market','Pet shop','Furniture','Boutique'];locations.shops.rooms.Boutique=[];locations.park.tabs=['Pavilion','Gardens'];locations.park.rooms.Pavilion=[];locations.park.rooms.Gardens=[];
const board2=document.getElementById('town-board');if(board2){const extras=[['library','Library'],['greenhouse','Greenhouse'],['giftshop','Gift shop'],['delivery','Delivery center'],['studio','Art studio'],['boutique','Boutique']];extras.forEach(([key,label])=>board2.insertAdjacentHTML('beforeend',`<button class="town-building service-building ${key}" data-location="${key==='boutique'?'shops':key}"><i class="roof ${key==='greenhouse'?'sage':'tile'}"></i><i class="smoke-stack"></i><i class="building-face"><b class="window left"></b><b class="door"></b><b class="window right"></b><i class="flower-box"></i></i><span>${label}</span></button>`));for(let i=0;i<8;i++)board2.insertAdjacentHTML('beforeend',`<div class="village-filler garden-cluster" style="left:${4+(i*17)%90}%;top:${12+(i*23)%78}%"></div>`);board2.insertAdjacentHTML('beforeend','<div class="village-filler fence-run" style="left:4%;top:43%"></div><div class="village-filler fence-run" style="right:6%;bottom:34%;transform:rotate(30deg) translateZ(20px)"></div>')}
let interiorXY={x:48,y:72},nearPhysical=null,cart=[];
function physicalCharacter(){return `<div class="physical-player character"><div class="character-legs"><i></i><i></i></div><div class="character-body"><i class="apron"></i></div><div class="character-head"><i class="hair back"></i><i class="face"><b class="eye left"></b><b class="eye right"></b><b class="smile"></b></i><i class="hair fringe"></i></div></div>`}
function positionObjects(items){return items.map((o,i)=>{const cols=6,x=2+(i%cols)*16,y=5+Math.floor(i/cols)*35;return `<button class="physical-object" data-type="${o[1]}" data-action-name="${o[2]}" style="left:${x}%;top:${y}%"><i class="object-model"></i><b class="object-name">${o[0]}</b></button>`}).join('')}
renderRoom=function(){const key=current+'|'+currentTab,items=physicalRooms[key]||physicalRooms[current+'|'+locations[current].tabs[0]]||[];$('#room').className='room physical-room '+current+'-'+currentTab.toLowerCase().replace(/\s+/g,'-');$('#room').innerHTML=`<div class="physical-shell"><div class="physical-window"></div><div class="curtain"></div><div class="hanging-plants"></div><div class="menu-board">${current==='bakery'?'TODAY · BREAD · CAKES · COFFEE · TEA':locations[current].title}</div><div class="physical-stage">${positionObjects(items)}</div>${physicalCharacter()}</div>`;document.querySelector('.physical-player').style.left=interiorXY.x+'%';document.querySelector('.physical-player').style.top=interiorXY.y+'%'};
document.body.insertAdjacentHTML('beforeend','<div class="proximity-prompt" id="proximity-prompt">E · Interact</div>');
document.addEventListener('keydown',e=>{if(!document.getElementById('location').classList.contains('active'))return;const m={arrowup:[0,-3],w:[0,-3],arrowdown:[0,3],s:[0,3],arrowleft:[-3,0],a:[-3,0],arrowright:[3,0],d:[3,0]},v=m[e.key.toLowerCase()];if(v){interiorXY.x=Math.max(2,Math.min(94,interiorXY.x+v[0]));interiorXY.y=Math.max(22,Math.min(86,interiorXY.y+v[1]));const p=document.querySelector('.physical-player');if(p){p.style.left=interiorXY.x+'%';p.style.top=interiorXY.y+'%'}const objs=[...document.querySelectorAll('.physical-object')];nearPhysical=objs.reduce((best,o)=>{const d=Math.hypot(parseFloat(o.style.left)-interiorXY.x,parseFloat(o.style.top)-interiorXY.y);return !best||d<best.d?{o,d}:best},null);objs.forEach(o=>o.classList.toggle('near',nearPhysical&&nearPhysical.o===o&&nearPhysical.d<18));document.getElementById('proximity-prompt').classList.toggle('show',nearPhysical&&nearPhysical.d<18)}if(e.key.toLowerCase()==='e'&&nearPhysical?.d<18)interactPhysical(nearPhysical.o)});
function interactPhysical(el){const action=el.dataset.actionName,name=el.querySelector('.object-name').textContent;if(action==='Enter Kitchen'){currentTab='Kitchen';renderTabs();renderRoom();return}if(current==='bakery'&&['Bake Bread','Bake Pastry','Bake Cake','Bake Cupcakes','Bake Cookies','Bake Pie','Make Sandwich','Make Coffee','Make Tea','Blend Smoothie'].includes(action)){kitchen(action.replace(/^(Bake|Make|Blend) /,'')==='Cupcakes'?'Cake':action.replace(/^(Bake|Make|Blend) /,''));return}if(current==='shops'&&currentTab==='Furniture'){shop('furniture');return}if(current==='shops'&&currentTab==='Pet shop'){shop('pets');return}if(current==='shops'&&currentTab==='Market'){if(action==='Checkout')marketCheckout();else{cart.push(name);toast(`${name} added to cart`)}return}if(action==='Unlock Recipe'){state.xp+=25;toast('New recipe inspiration unlocked! +25 XP');save();return}if(action==='Accept Job'){state.deliveryJob='Fresh bread to Willow Cottage';toast('Delivery accepted');save();return}if(action==='Complete Job'){state.coins+=120;state.deliveryJob=null;updateHUD();toast('Delivery complete · +120 coins');return}if(action==='Sleep and Save'){state.day++;state.minute=480;updateHUD();toast('Game saved · Good morning!');return}toast(`${action}: ${name}`)}
function marketCheckout(){if(!cart.length){toast('Your cart is empty');return}modal(`<h2>Market checkout</h2><p>${cart.length} items are being scanned and packed.</p><div class="checkout-progress running"><i></i></div><button class="game-btn" id="finish-checkout" disabled>Scanning… 10 seconds</button>`);setTimeout(()=>{const b=document.getElementById('finish-checkout');if(b){b.disabled=false;b.textContent='Finish';b.onclick=()=>{const cost=cart.length*8;if(state.coins>=cost){state.coins-=cost;cart.forEach(x=>state.inventory[x]=(state.inventory[x]||0)+1);cart=[];updateHUD();$('#modal-wrap').hidden=true;toast('Groceries collected')}else toast('Not enough coins')}}},10000)}
document.addEventListener('click',e=>{const o=e.target.closest('.physical-object');if(o)interactPhysical(o)});
const populatedRender=renderRoom;renderRoom=function(){populatedRender();if(current==='bakery'&&currentTab==='Café')document.querySelector('.physical-shell')?.insertAdjacentHTML('beforeend','<i class="room-npc npc-a"></i><i class="room-npc npc-b"></i>');if(current==='shops'&&currentTab==='Market')document.querySelector('.physical-shell')?.insertAdjacentHTML('beforeend','<i class="room-npc npc-a"></i><i class="room-npc npc-c"></i>');if(current==='shops'&&currentTab==='Pet shop')document.querySelector('.physical-shell')?.insertAdjacentHTML('beforeend','<i class="room-npc npc-a"></i><i class="npc-pet"></i>')};
document.querySelector('.service-building.boutique')?.addEventListener('click',()=>setTimeout(()=>{currentTab='Boutique';renderTabs();renderRoom();document.querySelectorAll('#room-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='Boutique'))},760));
