const locations={
 bakery:{kicker:'YOUR BAKERY',title:'Honeybell Bakery',desc:'A sunlit patisserie filled with warm bread, mint cabinetry and the gentle clink of teacups.',tabs:['Café','Kitchen'],bg:'assets/honeybell-village.png',rooms:{
  'Café':[['🍰','Cake counter','Fresh layers & berries','pink'],['☕','Espresso bar','Coffee, tea & cocoa','mint'],['🪑','Window tables','A cozy place to stay','gold'],['🧁','Daily special','Fairy sprinkle cupcake','lavender'],['🥐','Pastry case','Baked this morning','gold'],['🌷','Atmosphere','Flowers raise customer mood','mint']],
  'Kitchen':[['🔥','Baking range','Prepare today’s orders','gold'],['🥣','Prep island','Mix, knead & decorate','mint'],['🧊','Cold pantry','Fresh village ingredients','pink'],['🍞','Bread station','7 recipes unlocked','gold'],['🧁','Pastry station','7 recipes unlocked','lavender'],['🧼','Wash station','Keep the kitchen shining','mint']] }},
 cottage:{kicker:'WELCOME HOME',title:'Rosemary Cottage',desc:'A flower-wrapped thatched cottage with gingham linens, warm timber and room for every treasure.',tabs:['Living room','Wardrobe'],bg:'assets/honeybell-village.png',rooms:{
  'Living room':[['🛋️','Cozy corner','Soft linen & knitted throws','pink'],['🔥','Hearth','Warm through rainy evenings','gold'],['🫖','Dining nook','Tea for four','mint'],['📚','Bookcase','Recipes and fairy tales','gold'],['🪴','Window garden','Herbs & trailing ivy','mint'],['🐈','Pet bed','A very sunny nap spot','lavender']],
  'Wardrobe':[['👗','Cottage dresses','Florals and soft linen','pink'],['🧥','Layers','Cardigans & aprons','mint'],['👢','Shoes','Boots and sandals','gold'],['👒','Accessories','Straw hats & flowers','lavender']] }},
 shops:{kicker:'MARKET ROW',title:'The Cottage Shops',desc:'Three neighboring shops under striped awnings, each stocked with village finds and friendly faces.',tabs:['Market','Pet shop','Furniture'],bg:'assets/honeybell-village.png',rooms:{
  'Market':[['🥕','Fresh produce','Carrots, berries & greens','mint'],['🥛','Dairy shelf','Milk, eggs & butter','gold'],['🥫','Pantry','Flour, sugar & preserves','pink'],['🥖','Bakery shelf','Your goods on display','gold'],['🧃','Cool drinks','Juice & lemonade','mint'],['🛒','Checkout','Today’s special offers','lavender']],
  'Pet shop':[['🐕','Puppy nook','Friendly village companions','gold'],['🐈','Kitten window','Soft beds & sunny naps','pink'],['🐇','Small friends','Rabbits and guinea pigs','mint'],['🐟','Aquarium','Colorful little swimmers','lavender'],['🦴','Treat shelf','Snacks and toys','gold'],['🛏️','Pet furniture','Beds, trees & hutches','mint']],
  'Furniture':[['🛋️','Cottage seating','Sofas and armchairs','pink'],['🪵','Dining collection','Rounded honey-oak tables','gold'],['💡','Lighting','Soft lamps & lanterns','lavender'],['🪴','Décor','Rugs, pots & cushions','mint'],['🛏️','Bedroom','Cozy quilts & side tables','pink'],['✨','Luxury room','Special rotating pieces','gold']] }},
 park:{kicker:'WILLOW PARK',title:'Picnic beneath the trees',desc:'Dense daisies, clover and old trees surround a lace-edged picnic blanket beside the stream.',tabs:['Picnic meadow','Garden'],bg:'assets/honeybell-village.png',rooms:{
  'Picnic meadow':[['🧺','Picnic blanket','Share a village lunch','pink'],['🌳','Old willow','Rest in the shade','mint'],['📷','Memory spot','Take a keepsake photo','gold'],['🦋','Butterfly patch','Quietly watch them dance','lavender']],
  'Garden':[['🌼','Wildflower walk','Daisies & buttercups','gold'],['🌿','Herb garden','Mint, thyme & lavender','mint'],['🌉','Little bridge','Listen to the stream','pink'],['🐦','Bird grove','A favorite village perch','lavender']] }}
};
const names=['Emma Brooks','Oliver Baker','Lily Foster','Noah Wilson','Sophia Carter','Henry Green','Ruby Walker','Lucas Reed'];
const traits=['Cheerful · Gardener','Shy · Book Lover','Friendly · Coffee Lover','Calm · Animal Lover','Funny · Artist','Kind · Retired Baker','Bright · Student','Warm · Teacher'];
const foods=['Strawberry Cake','Croissant','Apple Pie','Fairy Cupcake','Cinnamon Roll','Peach Tea','Baguette','Berry Smoothie'];
let state=JSON.parse(localStorage.getItem('honeybell-save')||'null')||{coins:1000,stars:12,day:1,minute:540,sound:true,startingCoinsGranted:true,npcs:names.map((name,i)=>({name,trait:traits[i],favorite:foods[i],birthday:1+((i*7+1)%28),friendship:1+(i%3),gifted:false}))};
if(!state.startingCoinsGranted){state.coins=Math.max(1000,state.coins||0);state.startingCoinsGranted=true}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); let current='bakery',currentTab='Café';
function save(){localStorage.setItem('honeybell-save',JSON.stringify(state))} function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function updateHUD(){ $('#coins').textContent=state.coins;$('#stars').textContent=state.stars;$('#season').textContent=`Spring · Day ${state.day}`; const h=Math.floor(state.minute/60),m=state.minute%60;$('#clock').textContent=`${h>12?h-12:h}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`;const birthday=state.npcs.some(n=>n.birthday===state.day&&!n.gifted);$('#birthday-dot').style.display=birthday?'block':'none';save() }
function showScene(id){$$('.scene').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.dock button').forEach(x=>x.classList.remove('active'));const b=id==='world'?'[data-action="home"]':'[data-location="'+current+'"]';$('.dock '+b)?.classList.add('active')}
function openLocation(key){current=key;const l=locations[key];currentTab=l.tabs[0];$('#loc-kicker').textContent=l.kicker;$('#loc-title').textContent=l.title;$('#loc-desc').textContent=l.desc;$('.location-bg').style.backgroundImage=`url('${l.bg}')`;renderTabs();renderRoom();showScene('location')}
function renderTabs(){const l=locations[current];$('#room-tabs').innerHTML=l.tabs.map((t,i)=>`<button class="${i===0?'active':''}" data-tab="${t}">${t}</button>`).join('')}
function renderRoom(){const data=locations[current].rooms[currentTab];$('#room').innerHTML=data.map(z=>`<button class="zone ${z[3]}" data-zone="${z[1]}"><span class="art">${z[0]}</span><h3>${z[1]}</h3><p>${z[2]}</p></button>`).join('')}
function modal(html){$('#modal-content').innerHTML=html;$('#modal-wrap').hidden=false}
function friends(){const today=state.npcs.filter(n=>n.birthday===state.day);modal(`<h2>Village friends</h2><p class="sub">Every neighbor has a birthday and remembers your kindness.</p>${today.length?`<div class="birthday">🎂 <strong>Birthday today!</strong><br>${today.map(n=>n.name).join(', ')} is visiting the bakery.</div>`:''}<div>${state.npcs.map((n,i)=>`<div class="friend"><span class="avatar">${['👩🏽','👨🏻','👩🏻','👨🏾','👩🏾','👴🏻','👧🏻','👨🏼'][i]}</span><span class="friend-info"><b>${n.name}</b><small>${n.trait} · Birthday: Spring ${n.birthday}</small><small>Favorite: ${n.favorite}</small></span><span class="hearts">${'♥'.repeat(n.friendship)}${'♡'.repeat(5-n.friendship)}</span>${n.birthday===state.day&&!n.gifted?`<button class="primary gift" data-npc="${i}">Give dessert</button>`:''}</div>`).join('')}</div>`)}
function calendar(){modal(`<h2>Spring calendar</h2><p class="sub">Birthdays bring neighbors to Honeybell Bakery.</p><div class="cards">${state.npcs.map(n=>`<div class="card"><h3>Spring ${n.birthday}</h3><p>🎂 ${n.name}<br>Favorite: ${n.favorite}</p></div>`).join('')}</div>`)}
function inventory(){modal(`<h2>Baker’s satchel</h2><p class="sub">Ingredients and little gifts collected around the village.</p><div class="cards"><div class="card"><h3>🥚 Farm eggs · 8</h3><p>Fresh from the market.</p></div><div class="card"><h3>🍓 Strawberries · 12</h3><p>Perfect for birthday cake.</p></div><div class="card"><h3>🎁 Small gifts · 3</h3><p>A thoughtful friendship boost.</p></div><div class="card"><h3>🌾 Flour · 16</h3><p>Stone-ground and ready.</p></div></div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.location){openLocation(b.dataset.location);return}if(b.dataset.tab){currentTab=b.dataset.tab;$$('#room-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderRoom();return}if(b.dataset.zone){state.minute=Math.min(1080,state.minute+15);updateHUD();toast(`${b.dataset.zone} · 15 minutes passed`);return}if(b.classList.contains('gift')){const n=state.npcs[+b.dataset.npc];n.gifted=true;n.friendship=Math.min(5,n.friendship+2);state.stars+=5;updateHUD();friends();toast(`A perfect birthday surprise for ${n.name}! +2 friendship`);return}switch(b.dataset.action){case'home':showScene('world');break;case'enter':openLocation('bakery');break;case'hide-welcome':$('.welcome').style.display='none';break;case'calendar':calendar();break;case'friends':friends();break;case'inventory':inventory();break;case'more':modal('<h2>Village journal</h2><p class="sub">Your cozy life, saved automatically.</p><div class="cards"><div class="card"><h3>Today’s goal</h3><p>Serve 5 happy customers.</p></div><div class="card"><h3>Bakery mood</h3><p>🌸🌸🌸 Warm & welcoming</p></div></div>');break;case'close':$('#modal-wrap').hidden=true;break;case'sound':state.sound=!state.sound;b.textContent=state.sound?'♪':'×';toast(state.sound?'Ambience on':'Ambience off');updateHUD();break}});
$('#modal-wrap').addEventListener('click',e=>{if(e.target.id==='modal-wrap')e.currentTarget.hidden=true});updateHUD();
state.wasd=state.wasd||false;state.created=state.created||false;state.player=state.player||{name:'Your Baker',x:48,y:61};
function startSettings(){modal(`<h2>Settings</h2><div class="cards"><div class="card"><h3>Music & birdsong</h3><button data-launch="sound">${state.sound?'On':'Off'}</button></div><div class="card"><h3>WASD movement</h3><button data-launch="wasd">${state.wasd?'On':'Off'}</button></div></div>`)}
function showCreator(){const s=$('#start-screen');s.classList.add('leaving');setTimeout(()=>{s.classList.add('hidden');$('#creator').classList.add('active')},1100)}
function enterVillage(){$('#creator').classList.remove('active');showScene('world');$('#player').style.left=state.player.x+'%';$('#player').style.top=state.player.y+'%';$('#wasd-hint').textContent=state.wasd?'WASD enabled':''}
function movePlayer(dx,dy){if(!$('#world').classList.contains('active')||!$('#start-screen').classList.contains('hidden'))return;state.player.x=Math.max(4,Math.min(94,state.player.x+dx));state.player.y=Math.max(13,Math.min(82,state.player.y+dy));const player=$('#player');player.style.left=state.player.x+'%';player.style.top=state.player.y+'%';player.classList.add('walking');clearTimeout(movePlayer.stopTimer);movePlayer.stopTimer=setTimeout(()=>player.classList.remove('walking'),180);save()}
$('#creator-form').addEventListener('input',()=>{$('#preview-name').textContent=$('#char-name').value||'Your Baker';$('#avatar-large .hair').style.color=$('#hair-color').value;$('#avatar-large .face').style.background=$('#skin-tone').value;$('#avatar-large .accessory').textContent=$('#char-accessory').value});
$('#creator-form').addEventListener('submit',e=>{e.preventDefault();state.player.name=$('#char-name').value;state.player.gender=$('#char-gender').value;state.created=true;save();enterVillage()});
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),moves={arrowup:[0,-1.5],arrowdown:[0,1.5],arrowleft:[-1.2,0],arrowright:[1.2,0],w:[0,-1.5],s:[0,1.5],a:[-1.2,0],d:[1.2,0]};if(moves[k]){e.preventDefault();movePlayer(...moves[k])}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='new-game')showCreator();if(a==='continue'){if(state.created){$('#start-screen').classList.add('hidden');enterVillage()}else showCreator()}if(a==='start-settings')startSettings();if(a==='themes')modal('<h2>Themes</h2><div class="cards"><div class="card"><h3>🌸 Spring Morning</h3><button data-theme="spring">Use theme</button></div><div class="card"><h3>🌙 Fairy Twilight</h3><button data-theme="twilight">Use theme</button></div></div>');if(a==='credits')modal('<h2>Credits</h2><p>Cottage Bakery: Fairy Life</p><div class="birthday">A peaceful friendship-focused bakery adventure. No romance, marriage, or children.</div>');if(a==='dismiss-narrator')$('#narrator').style.display='none';if(b.dataset.launch==='wasd'){state.wasd=!state.wasd;save();startSettings()}if(b.dataset.launch==='sound'){state.sound=!state.sound;save();startSettings()}if(b.dataset.theme){document.body.style.filter=b.dataset.theme==='twilight'?'hue-rotate(25deg) brightness(.82)':'none';$('#modal-wrap').hidden=true}});

// Connected gameplay systems
Object.assign(state,{level:state.level||1,xp:state.xp||0,energy:state.energy||100,inventory:state.inventory||{Flour:8,Eggs:6,Milk:5,Sugar:6,Butter:4},stock:state.stock||{Croissant:5,Latte:5,'Strawberry Cake':3,Cookies:6,Lemonade:4},pet:state.pet||null,furniture:state.furniture||[],decor:state.decor||1,shift:state.shift||{active:false,served:0,earned:0,rating:5},talked:state.talked||{}});
if(state.stock['Apple Pie']==null)state.stock['Apple Pie']=1;
const catalog={market:[['Flour',8,'🌾'],['Eggs',6,'🥚'],['Milk',7,'🥛'],['Sugar',5,'🧂'],['Butter',9,'🧈'],['Strawberries',12,'🍓']],pets:[['White Rabbit',250,'🐇'],['Hamster',300,'🐹'],['Budgie',400,'🐦'],['Orange Cat',750,'🐈'],['Beagle',850,'🐕'],['Golden Retriever',1500,'🦮']],furniture:[['Wooden Chair',80,'🪑'],['Simple Rug',150,'🧶'],['Small Lamp',220,'💡'],['Tea Table',450,'🫖'],['Cottage Sofa',600,'🛋️'],['Fireplace',850,'🔥']]};
const recipes={Bread:[['White Bread',8,50,'🍞'],['Brioche',18,110,'🥯'],['Baguette',12,75,'🥖']],Pastry:[['Croissant',12,90,'🥐'],['Cinnamon Roll',18,130,'🌀'],['Cream Puff',22,150,'🍥']],Cake:[['Strawberry Cake',25,160,'🍰'],['Birthday Cake',180,1200,'🎂'],['Cheesecake',28,180,'🍰']],Drinks:[['Latte',10,90,'☕'],['Peach Tea',7,55,'🍵'],['Lemonade',6,45,'🥤']],Cookies:[['Cookies',5,35,'🍪'],['Brownie',10,60,'🟫'],['Fairy Cupcake',20,120,'🧁']]};
const oldOpenLocation=openLocation;openLocation=function(key){const load=$('#loading-screen');load.classList.add('show');setTimeout(()=>{oldOpenLocation(key);load.classList.remove('show')},700)};
renderRoom=function(){const data=locations[current].rooms[currentTab],slug=(current+'-'+currentTab).toLowerCase().replace(/[^a-z]+/g,'-');$('#room').className='room designed-room '+slug;$('#room').innerHTML=`<div class="interior-shell"><div class="room-window"><i></i><i></i><span>🌿</span></div><div class="ceiling-light">✦</div><div class="wall-art">${current==='bakery'?'PATISSERIE':current==='cottage'?'HOME SWEET HOME':current==='shops'?'VILLAGE GOODS':'WILLOW PARK'}</div><div class="interior-stage">${data.map((z,i)=>`<button class="furniture-piece piece-${i+1}" data-zone="${z[1]}" title="${z[2]}"><span>${z[0]}</span><b>${z[1]}</b></button>`).join('')}</div><div class="interior-player character mini"><div class="character-legs"><i></i><i></i></div><div class="character-body"><i class="apron"></i></div><div class="character-head"><i class="hair back"></i><i class="face"><b class="eye left"></b><b class="eye right"></b><b class="smile"></b></i><i class="hair fringe"></i></div></div></div>${current==='bakery'&&currentTab.includes('Caf')?'<button class="register-button" data-game="shift">🛎️ <b>Bakery Register</b><small>Start shift & serve customers</small></button>':''}`};
function shop(kind){const title=kind==='market'?'Village Market':kind==='pets'?'Cottage Pet Shop':'Furniture Shop';modal(`<h2>${title}</h2><p class="sub">Today’s hand-picked selection · Coins: ${state.coins}</p><div class="game-grid">${catalog[kind].map((x,i)=>`<div class="game-item ${kind==='pets'?'pet-card':''}"><span class="${kind==='pets'?'pet-icon':''}">${x[2]}</span><h3>${x[0]}</h3><small>${kind==='pets'?'A friendly village companion':'Common · In stock'}</small><span class="price">◉ ${x[1]}</span><br><button class="game-btn" data-buy="${kind}" data-index="${i}">${kind==='pets'?'Adopt':'Buy'}</button></div>`).join('')}</div>`)}
function kitchen(station='Bread'){modal(`<h2>Bakery kitchen</h2><p class="sub">Choose a recipe, then measure, mix, bake and decorate it yourself. Better technique produces higher-quality food.</p><div class="station-list">${Object.keys(recipes).map(s=>`<button data-station="${s}" class="${s===station?'active':''}">${s}</button>`).join('')}</div><div>${recipes[station].map((r,i)=>`<div class="recipe-row"><span>${r[3]}</span><div><b>${r[0]}</b><small>Hands-on baking · quality affects value</small></div><button class="game-btn" data-skill-launch-recipe="${r[0]}">Bake interactively</button></div>`).join('')}</div>`)}
function shift(){if(!state.shift.active){modal(`<h2>Open Honeybell Bakery?</h2><p class="sub">You choose when work begins. The village remains yours to explore.</p><div class="shift-banner"><span>🕰️ Current time: ${$('#clock').textContent}</span><button data-game="start-shift">Start Shift</button></div>`);return}const items=Object.keys(state.stock).filter(k=>state.stock[k]>0),food=items[Math.floor(Math.random()*items.length)]||'Croissant';const guest=state.npcs[Math.floor(Math.random()*state.npcs.length)];modal(`<h2>Bakery shift</h2><div class="stat-row"><div class="stat"><b>${state.shift.served}</b><small>Served</small></div><div class="stat"><b>◉ ${state.shift.earned}</b><small>Earned</small></div><div class="stat"><b>${state.shift.rating.toFixed(1)} ★</b><small>Rating</small></div><div class="stat"><b>${state.stock[food]||0}</b><small>${food}</small></div></div><div class="order-card"><div class="order-head"><b>🙂 ${guest.name}</b><span>Order bubble</span></div><h3>${food} + ${Math.random()>.5?'Latte':'Peach Tea'}</h3><div class="patience"><i></i></div><button class="game-btn" data-serve="${food}">Serve correct order</button> <button class="game-btn" data-game="end-shift">Close early</button></div>`)}
function summary(){state.shift.active=false;modal(`<h2>Shift Over! Great work today!</h2><div class="stat-row"><div class="stat"><b>◉ ${state.shift.earned}</b><small>Earned</small></div><div class="stat"><b>${state.shift.served}</b><small>Customers</small></div><div class="stat"><b>${state.shift.rating.toFixed(1)} ★</b><small>Rating</small></div><div class="stat"><b>+${state.shift.served*10}</b><small>XP</small></div></div><p>Most popular: Croissant · Friendship progress +${Math.ceil(state.shift.served/2)}</p><button class="game-btn" data-game="finish-day">Continue exploring</button>`);state.xp+=state.shift.served*10;save()}
function cottageAction(name){const actions={"Cozy corner":['Sit and relax',10],Hearth:['Relax by the fire',12],'Dining nook':['Drink tea',8],Bookcase:['Read for inspiration',5],'Pet bed':['Play with pet',8]};const a=actions[name]||['Enjoy the cottage',5];state.energy=Math.min(100,state.energy+a[1]);toast(`${a[0]} · Energy +${a[1]}`);save()}
function parkGame(){const reward=20+Math.floor(Math.random()*41);state.coins+=reward;state.energy=Math.max(0,state.energy-3);updateHUD();toast(`You collected flowers and earned ${reward} coins!`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.zone){if(current==='shops'){if(currentTab==='Market')shop('market');else if(currentTab==='Pet shop')shop('pets');else shop('furniture')}else if(current==='cottage')cottageAction(b.dataset.zone);else if(current==='park')parkGame();else if(current==='bakery'&&currentTab==='Kitchen')kitchen()}if(b.dataset.game==='shift')shift();if(b.dataset.game==='start-shift'){state.shift={active:true,served:0,earned:0,rating:5};state.minute=Math.max(state.minute,480);save();shift()}if(b.dataset.serve){if((state.stock[b.dataset.serve]||0)>0){state.stock[b.dataset.serve]--;const pay=50+Math.floor(Math.random()*80);state.coins+=pay;state.shift.earned+=pay;state.shift.served++;state.minute+=20;updateHUD();if(state.minute>=1140)summary();else shift()}else toast('Out of stock — visit the market!')}if(b.dataset.game==='end-shift')summary();if(b.dataset.game==='finish-day'){$('#modal-wrap').hidden=true;showScene('world')}if(b.dataset.station)kitchen(b.dataset.station);if(b.dataset.cook){const r=recipes[b.dataset.cook][+b.dataset.recipe];if(state.coins>=r[1]){state.coins-=r[1];state.stock[r[0]]=(state.stock[r[0]]||0)+3;state.energy=Math.max(0,state.energy-4);updateHUD();toast(`${r[0]} baked · +3 stock`);kitchen(b.dataset.cook)}else toast('Not enough coins for ingredients')}if(b.dataset.buy){const item=catalog[b.dataset.buy][+b.dataset.index];if(state.coins<item[1]){toast('Not enough coins');return}state.coins-=item[1];if(b.dataset.buy==='market')state.inventory[item[0]]=(state.inventory[item[0]]||0)+5;if(b.dataset.buy==='pets')state.pet={name:item[0],happiness:50,icon:item[2]};if(b.dataset.buy==='furniture'){state.furniture.push(item[0]);state.decor++;}updateHUD();toast(`${b.dataset.buy==='pets'?'Adopted':'Purchased'} ${item[0]}!`);shop(b.dataset.buy)}});
setInterval(()=>{if(state.shift.active){state.minute+=10;if(state.minute>=1140)summary();updateHUD()}const phase=state.minute<660?'morning':state.minute<960?'afternoon':'evening';document.body.classList.remove('time-morning','time-afternoon','time-evening');document.body.classList.add('time-'+phase)},30000);
