// Isometric town camera, decoration placement, and furniture purchasing.
const decorateState={active:false,drag:null,offsetX:0,offsetY:0};
function updateTownCamera(){const p=state.player||{x:48,y:61};const x=(50-p.x)*1.8,y=(50-p.y)*1.1;document.getElementById('town-camera')?.style.setProperty('translate',`${x}px ${y}px`)}
const baseMove=movePlayer;movePlayer=function(dx,dy){baseMove(dx,dy);updateTownCamera()};
function addDecorButton(){if(current!=='cottage'&&current!=='bakery')return;const tabs=document.getElementById('room-tabs');if(tabs&&!tabs.querySelector('[data-decorate]'))tabs.insertAdjacentHTML('beforeend',`<button data-decorate class="${decorateState.active?'active':''}">${decorateState.active?'✓ Finish':'✥ Decorate'}</button>`)}
const baseRender=renderRoom;renderRoom=function(){baseRender();addDecorButton();restoreFurniturePositions()};
function restoreFurniturePositions(){const key=current+'|'+currentTab,positions=state.furniturePositions?.[key]||{};document.querySelectorAll('.furniture-piece').forEach((el,i)=>{if(positions[i]){el.style.left=positions[i].x+'%';el.style.top=positions[i].y+'%';el.style.right='auto';el.style.bottom='auto'}})}
function furnitureChoices(label){const same=catalog.furniture.filter(x=>x[0].toLowerCase().includes(label.split(' ')[0].toLowerCase()));const choices=same.length?same:catalog.furniture;modal(`<h2>${label}</h2><p class="sub">Choose a piece for your cottage. Purchased furniture becomes available in Decoration Mode.</p><div class="game-grid">${choices.map((x,i)=>`<div class="game-item"><div class="furniture-preview furniture-${i}">${x[2]}</div><h3>${x[0]}</h3><small>${i<2?'Common':'Cozy'} · Smooth oak and linen</small><span class="price">◉ ${x[1]}</span><br><button class="game-btn" data-buy-choice="${catalog.furniture.indexOf(x)}">Buy furniture</button></div>`).join('')}</div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.decorate!==undefined){decorateState.active=!decorateState.active;document.querySelector('.designed-room')?.classList.toggle('decorate-mode',decorateState.active);b.textContent=decorateState.active?'✓ Finish':'✥ Decorate';toast(decorateState.active?'Drag furniture to arrange the room':'Room layout saved')}if(b.dataset.buyChoice!==undefined){const item=catalog.furniture[+b.dataset.buyChoice];if(state.coins<item[1]){toast('Not enough coins');return}state.coins-=item[1];state.furniture.push(item[0]);state.decor++;updateHUD();toast(`${item[0]} added to Decoration Mode`);furnitureChoices(item[0])}if(current==='shops'&&currentTab==='Furniture'&&b.classList.contains('furniture-piece')){e.stopImmediatePropagation();furnitureChoices(b.dataset.zone)}} ,true);
document.addEventListener('pointerdown',e=>{if(!decorateState.active)return;const item=e.target.closest('.furniture-piece');if(!item)return;e.preventDefault();decorateState.drag=item;const r=item.getBoundingClientRect();decorateState.offsetX=e.clientX-r.left;decorateState.offsetY=e.clientY-r.top;item.setPointerCapture?.(e.pointerId);item.classList.add('dragging')});
document.addEventListener('pointermove',e=>{const item=decorateState.drag;if(!item)return;const stage=document.querySelector('.interior-stage'),r=stage.getBoundingClientRect();const x=Math.max(0,Math.min(88,(e.clientX-r.left-decorateState.offsetX)/r.width*100));const y=Math.max(0,Math.min(75,(e.clientY-r.top-decorateState.offsetY)/r.height*100));item.style.left=x+'%';item.style.top=y+'%';item.style.right='auto';item.style.bottom='auto'});
document.addEventListener('pointerup',()=>{const item=decorateState.drag;if(!item)return;item.classList.remove('dragging');const key=current+'|'+currentTab,index=[...document.querySelectorAll('.furniture-piece')].indexOf(item);state.furniturePositions=state.furniturePositions||{};state.furniturePositions[key]=state.furniturePositions[key]||{};state.furniturePositions[key][index]={x:parseFloat(item.style.left),y:parseFloat(item.style.top)};save();decorateState.drag=null});
document.querySelectorAll('.town-building').forEach(b=>b.addEventListener('mouseenter',()=>document.getElementById('door-prompt').hidden=false));document.querySelectorAll('.town-building').forEach(b=>b.addEventListener('mouseleave',()=>document.getElementById('door-prompt').hidden=true));updateTownCamera();
function openCottageInterior(){openLocation('cottage');setTimeout(()=>{currentTab='Living room';renderTabs();renderRoom();document.querySelectorAll('#room-tabs button').forEach((button,index)=>button.classList.toggle('active',index===0))},760)}
document.getElementById('cottage-nav-button')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openCottageInterior()});
document.querySelector('.building-cottage')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openCottageInterior()});
